name: Build Resource Pack

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Create resource pack ZIP
        run: |
          zip -r fightclub-resourcepack.zip . \
            -x ".git/*" \
            -x ".github/*" \
            -x "fightclub-resourcepack.zip" \
            -x "README.md"

      - name: Calculate SHA-1
        id: sha1
        run: |
          SHA1=$(sha1sum fightclub-resourcepack.zip | cut -d ' ' -f 1)
          echo "SHA-1: $SHA1"
          echo "sha1=$SHA1" >> "$GITHUB_OUTPUT"

      - name: Delete previous release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release delete resourcepack-latest --yes || true
          git push --delete origin resourcepack-latest || true

      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create resourcepack-latest \
            fightclub-resourcepack.zip \
            --title "Fightclub Resource Pack" \
            --notes "Latest version of the Fightclub resource pack." \

          SHA-1: ${{ steps.sha1.outputs.sha1 }}" \
            --latest